config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flights#index"
  resources :flights, only: :index
  resources :bookings, only: %i[show new create]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'

  def self.airport_options
    all.map { |a| [a.code, a.id] }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'

  has_many :bookings
  has_many :passengers, through: :bookings

  def self.dates_options
    order(:date).pluck(:date).uniq.map { |d| [d.strftime('%d/%m/%Y'), d] }
  end

  def format_date
    date.strftime('%d/%m/%Y')
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
    @passengers = @booking.passengers
  end

  def new
    passengers_amount = params[:flight][:passengers].to_i

    @booking = Booking.new
    passengers_amount.times { @booking.passengers.build }

    @flight = Flight.find(params[:flight][:flight_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @flight = Flight.find(params[:booking][:flight_id])

    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight = Flight.new
    @options = [Airport.airport_options, Flight.dates_options, [['1', 1], ['2', 2], ['3', 3], ['4', 4]]]
    return unless params[:flight]

    @passengers = params[:flight][:passengers]
    @flights = Flight.where(flight_search_params)
    @departure_airport = Airport.find(params[:flight][:departure_airport_id]).code
    @arrival_airport = Airport.find(params[:flight][:arrival_airport_id]).code
  end

  private

  def flight_search_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<div class="page-title center">
  <h1 class="white-text">Your Fligth:</h1>
  <h3 class="subtitle"><%= @flight.departure_airport.code %> | <%= @flight.arrival_airport.code %> | <%= @flight.format_date %></h2>
</div>

<div class="flight-form">
  <div class="center">
    <h2 class="white-text">Passenger Info</h2>
  </div>
  <%= form_with model: @booking do |form| %>
    <%= form.hidden_field :flight_id, value: @flight.id  %>
    <%= form.fields_for :passengers do |passenger_form| %>
    <div class="passengers-section">
    <div class="form-section passenger-count">
      <p class="white-text passenger-text">Passenger <%= passenger_form.index + 1 %> </p>
    </div>

      <div class="form-section passenger-info">
        <%= passenger_form.label :name %>
        <%= passenger_form.text_field :name %>
      </div>
      <div class="form-section passenger-info">
        <%= passenger_form.label :email %>
        <%= passenger_form.email_field :email %>
      </div>
    </div>
    <% end %>
    <div class="submit-section">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="page-title center">
  <h1 class="white-text">Booking Details</h1>
</div>

<div class="info-card">
  <div class="card-title center">
    <h2>Flight Details</h2>
  </div>
  <div class="date-section card-border center">
    <h3><%= @flight.format_date %></h3>
  </div>
  <div class="card-info-section">
    <div class="info">
      <p>Departure</p>
      <p><%= @flight.departure_airport.code %></p>
    </div>
    <div class="info">
      <p>Duration</p>
      <p><%= @flight.duration %></p>
    </div>
    <div class="info">
      <p>Arrival</p>
      <p><%= @flight.arrival_airport.code %></p>
    </div>
  </div>
</div>

<div class="info-card">
  <div class="card-title card-border center">
    <h2>Passengers Details</h2>
  </div>
  <div class="card-info-section">
    <div class="info spaced">
      <p class="info-title">Name</p>
      <% @passengers.each do |passenger| %>
        <p> <%= passenger.name %> </p>
      <% end %>
    </div>
    <div class="info spaced">
      <p class="info-title">Contact</p>
      <% @passengers.each do |passenger| %>
        <p> <%= passenger.email %> </p>
      <% end %>
    </div>
  </div>
</div>

app/views/flights/_search_flight_form.html.erb
<%= form_with model: flight, url: flights_path, method: :get do |form| %>
  <div class="selectors-section">
    <div class="form-section">
      <%= form.label :departure_airport, 'Origin:' %>
      <%= form.select(:departure_airport_id, @options[0]) %>
    </div> <br>
    <div class="form-section">
      <%= form.label :arrival_airport, 'Arrival:' %>
      <%= form.select(:arrival_airport_id, @options[0]) %>
    </div> <br>
    <div class="form-section">
      <%= form.label :date, 'Date:' %>
      <%= form.select(:date, @options[1]) %>
    </div> <br>
    <div class="form-section">
      <%= form.label :passengers, 'Passengers:' %>
      <%= form.select(:passengers, @options[2]) %>
    </div> <br>
  </div>
  <div class="submit-section">
    <div class="form-section">
      <%= form.submit 'Search' %>
    </div>
  </div>
<% end %>

app/views/flights/_search_result_form.html.erb
<% if flights.any? %>
  <div class="center">
      <h2 class="white-text">Showing Flights from <%= @departure_airport %> to <%= @arrival_airport %></h2>
  </div>
  <div class="flight-form">
    <%= form_with model: flights, url: 'bookings/new', method: :get do |form| %>
      <% flights.each do |flight| %>
        <div class="flight-details">
          <%= form.hidden_field :passengers, value: @passengers %>
          <div class="radio-section">
            <%= form.radio_button :flight_id, flight.id %>
          </div>
          <div class="info-section">
            <p><%= flight.departure_airport.code %></p>
            <p><%= flight.duration %></p>
            <p><%= flight.arrival_airport.code %></p>
          </div>
        </div>
      <% end %>
      <div class="submit-section">
        <%= form.submit 'Continue' %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="center">
    <h2 class="white-text">No Flights Found.</h2>
  </div>
<% end %>

app/views/flights/index.html.erb
<div class="page-title center">
  <h1 class="title-text white-text">Flights Booker</h1>
</div>

<div class="flight-form">
  <%= render 'search_flight_form', flight: @flight %>
</div>

<% if @flights %>
  <%= render 'search_result_form', flights: @flights %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>